version: 0.2

env:
  variables:
    AWS_REGION: us-west-2
    ECR_REPO_URI: 722136401996.dkr.ecr.us-west-2.amazonaws.com/virus-scan-lambda

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
      - "IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)"
      - echo "Image tag set to $IMAGE_TAG"

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo "Docker image pushed: $ECR_REPO_URI:$IMAGE_TAG"
      - printf '[{"name":"virus-scan-lambda","imageUri":"%s"}]' $ECR_REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
